#!/bin/zsh
# Will return the current branch name
# Usage example: git pull origin $(current_branch)

function current_branch() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo ${ref#refs/heads/}
}
