#!/bin/zsh
gitstat=$(git status 2>/dev/null | grep '\(# Untracked\|# Change\)')

if [[ $gitstat =~ "# Changes" ]] || [[ $gitstat =~ "# Changed" ]]; then
    echo -n "$ZSH_THEME_GIT_PROMPT_DIRTY"
else
    echo -n "$ZSH_THEME_GIT_PROMPT_CLEAN"
fi

if [[ $gitstat =~ "# Untracked" ]]; then
    echo -n "$ZSH_THEME_GIT_PROMPT_UNTRACKED"
fi
