(deftheme gruber-darker
  "Created 2012-03-08.")

(custom-theme-set-variables
 'gruber-darker
 '(frame-background-mode (quote dark)))

(custom-theme-set-faces
 'gruber-darker
 '(cursor ((t (:background "#ffdd33"))))
 '(font-lock-comment-face ((t (:foreground "#cc8c3c"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#cc8c3c"))))
 '(font-lock-doc-face ((t (:foreground "#73c936"))))
 '(font-lock-doc-string-face ((t (:foreground "#73c936"))))
 '(font-lock-string-face ((t (:foreground "#73c936"))))
 '(font-lock-keyword-face ((t (:foreground "#ffdd33"))))
 '(font-lock-builtin-face ((t (:foreground "#ffdd33"))))
 '(font-lock-function-name-face ((t (:foreground "#96a6c8"))))
 '(font-lock-variable-name-face ((t (:foreground "#f4f4ff"))))
 '(font-lock-preprocessor-face ((t (:foreground "#95a99f"))))
 '(font-lock-constant-face ((t (:foreground "#95a99f"))))
 '(font-lock-type-face ((t (:foreground "#95a99f"))))
 '(font-lock-warning-face ((t (:foreground "#f43841"))))
 '(font-lock-reference-face ((t (:foreground "#95a99f"))))
 '(trailing-whitespace ((t (:foreground "#000" :background "#f43841"))))
 '(link ((t (:foreground "#96A6C8" :underline t))))
 '(isearch ((t (:foreground "#000" :background "#f5f5f5"))))
 '(lazy-highlight ((t (:foreground "#f4f4ff" :background "#5f627f"))))
 '(isearch-fail ((t (:foreground "#000" :background "#f43841"))))
 '(fringe ((t (:background "#111" :foreground "#444"))))
 '(border ((t (:background "#111" :foreground "#444"))))
 '(mode-line ((t (:background "#453d41" :foreground "#fff"))))
 '(mode-line-buffer-id ((t (:background "#453d41" :foreground "#fff"))))
 '(mode-line-inactive ((t (:background "#453d41" :foreground "#999"))))
 '(minibuffer-prompt ((t (:foreground "#96A6C8"))))
 '(region ((t (:background "#484848"))))
 '(secondary-selection ((t (:background "#484951" :foreground "#F4F4FF"))))
 '(tooltip ((t (:background "#52494e" :foreground "#fff"))))
 '(show-paren-match ((t (:background "#52494e" :foreground "#f4f4ff"))))
 '(show-paren-mismatch ((t (:foreground "#f4f4ff" :background "#c73c3f"))))
 '(highlight ((t (:background "#282828" :foreground nil))))
 '(highlight-current-line-face ((t (:background "#282828" :foreground nil))))
 '(holiday-face ((t (:foreground "#f43841"))))
 '(info-xref ((t (:foreground "#96a6c8"))))
 '(info-visited ((t (:foreground "#9e95c7"))))
 '(font-latex-sectioning-5-face ((t (:foreground "#96a6c8" :bold t))))
 '(font-latex-bold-face ((t (:foreground "#95a99f" :bold t))))
 '(font-latex-italic-face ((t (:foreground "#95a99f" :italic t))))
 '(font-latex-math-face ((t (:foreground "#73c936"))))
 '(font-latex-string-face ((t (:foreground "#73c936"))))
 '(font-latex-warning-face ((t (:foreground "#f43841"))))
 '(font-latex-slide-title-face ((t (:foreground "#96a6c8"))))
 '(default ((t (:foreground "#e4e4ef" :background "#181818")))))

(provide-theme 'gruber-darker)