require './dotfiles'

task :install do
  linkables("python").each do |item|
    next if item == "python/requirements.txt"
    if item == 'python/ipython'
      target = "#{ENV["HOME"]}/.ipython"
      backup target
      `mkdir -p #{target}/profile_default`
      install_item 'python/ipython/ipython_config.py', "#{target}/profile_default/ipython_config.py"
    elsif item == 'python/virtualenv_hooks'
      next if not ENV["WORKON_HOME"]
      target = "#{ENV["WORKON_HOME"]}"
      `mkdir -p #{target}`
      install_item 'python/virtualenv_hooks/postactivate', "#{target}/postactivate"
    else
      install_item item
    end
  end
end

task :uninstall do
  linkables("python").each do |item|
    if item == 'python/ipython'
      target = "#{ENV["HOME"]}/.ipython"
      uninstall_item 'python/ipython/ipython_config.py', "#{target}/profile_default/ipython_config.py"
      restore target
    elsif item == 'python/virtualenv_hooks'
      next if not ENV["WORKON_HOME"]
      target = "#{ENV["WORKON_HOME"]}"
      uninstall_item 'python/virtualenv_hooks/postactivate', "#{target}/postactivate"
    else
      uninstall_item item
    end
  end
end

desc "Setup common python packages"
task :install_pip_tools do
    system %Q[pip install -U -r python/requirements.txt]
end

desc "Install python interpreter"
task :install_python do
    system %Q[brew install python --framework]
    `sudo rm /Library/Frameworks/Python.framework/Versions`
    `sudo ln -is $(find /usr/local/Cellar/python -type l -name Current) /Library/Frameworks/Python.framework/Versions`
    system %Q[/usr/local/share/python/easy_install pip]
    system %Q[/usr/local/share/python/pip install --upgrade distribute]
    system %Q[brew cleanup]
end
