require 'dotfiles'

task :install do
  linkables("python").each do |item|
    next if item == "python/requirements.txt"
    if item == 'python/ipython'
      target = "#{ENV["HOME"]}/.ipython"
      `mkdir -p #{target}/profile_default`
      install_item 'python/ipython/virtualenv.py', "#{target}/virtualenv.py"
      install_item 'python/ipython/ipython_config.py', "#{target}/profile_default/ipython_config.py"
    else
      install_item item
    end
  end
end

task :uninstall do
  linkables("python").each do |item|
    if item == 'python/ipython'
      target = "#{ENV["HOME"]}/.ipython"
      uninstall_item 'python/ipython/virtualenv.py', "#{target}/virtualenv.py"
      uninstall_item 'python/ipython/ipython_config.py', "#{target}/profile_default/ipython_config.py"
    else
      uninstall_item item
    end
  end
end

desc "Setup common python packages"
task :install_pip_tools do
    system %Q[pip install -U -r python/requirements.txt]
end

desc "Install python interpreter"
task :install_python do
    system %Q[brew install python --framework]
    `sudo rm /Library/Frameworks/Python.framework/Versions`
    `sudo ln -is $(find /usr/local/Cellar/python -type l -name Current) /Library/Frameworks/Python.framework/Versions`
    system %Q[/usr/local/share/python/easy_install pip]
    system %Q[/usr/local/share/python/pip install --upgrade distribute]
    system %Q[brew cleanup]
end
