require './dotfiles'

task :install do
  linkables("osx").each do |item|
    if item == 'osx/DefaultKeyBinding.dict'
      target = "#{ENV["HOME"]}/Library/KeyBindings"
      backup target
      `mkdir -p #{target}/`
      install_item 'osx/DefaultKeyBinding.dict', "#{target}/DefaultKeyBinding.dict"
    elsif item == 'osx/defaults.sh'
      `bash osx/defaults.sh`
    else
      install_item item
    end
  end
end

task :uninstall do
  linkables("osx").each do |item|
    if item == 'osx/DefaultKeyBinding.dict'
      target = "#{ENV["HOME"]}/Library/KeyBindings"
      uninstall_item 'osx/DefaultKeyBinding.dict', "#{target}/DefaultKeyBinding.dict"
      restore target
    elsif item == 'osx/defaults.sh'
      next
    else
      uninstall_item item
    end
  end
end
