# Load and register completion functions
fpath=(~/.zsh/completions ~/.zsh/bundle/zsh-completions/src $fpath)

# There be user-defined functions
fpath=(~/.zsh/functions $fpath)
autoload ~/.zsh/functions/*(:t)

# Load config files, if we're not in vim or some other terminal
if [[ $TERM != "dumb" ]]; then
    for config_file (~/.zsh/lib/*.zsh) source $config_file
    unset config_file

    # Load plugins
    for plugin_file (~/.zsh/plugins/*.zsh) source $plugin_file
    unset plugin_file
fi

# Use vim for git commits and stuff
export EDITOR="vim"

# Setup PAGER and less options
export PAGER=less
export LESS="-FiRX"
