desc "Update installed packages"
task :update do
  system %Q[brew update && brew outdated]
  system %Q[brew upgrade]
  system %Q[brew cleanup]
end

desc "Install common tools from homebrew packages"
task :brew do
    puts "Installing Homebrew packages..."
    packages = [
        "git",
        "ack",
        "ctags",
        "par",
        "proctools",
        "wget",
        "w3m",
        "tmux",
        "reattach-to-user-namespace --wrap-pbcopy-and-pbpaste"
    ]
    packages.each do |pack|
        system %Q[brew install #{pack}]
    end
    system %Q[brew link ctags]
    system %Q[brew cleanup]
end

desc "Install common tools from npm packages"
task :npm do
    puts "Installing npm packages..."
    packages = [
        "http-console",
        "jshint",
        "coffee-script"
    ]
    packages.each do |pack|
        system %Q[npm install -g #{pack}]
    end
end

desc "Install common gems"
task :gems do
    packages = [
        "cheat",
        "facter"
    ]
    packages.each do |pack|
        system %Q[gem install #{pack}]
    end
end

