desc "Update installed packages"
task :update do
  system %Q[brew update && brew outdated]
  system %Q[brew upgrade]
  system %Q[brew cleanup]
end

desc "Install common tools from homebrew packages"
task :brew do
    system %Q[brew bundle tools/Brewfile]
end

desc "Install common tools from npm packages"
task :npm do
    puts "Installing npm packages..."
    packages = [
        "http-console",
        "jshint",
        "coffee-script"
    ]
    packages.each do |pack|
        system %Q[npm install -g #{pack}]
    end
end

desc "Install common gems"
task :gems do
    packages = [
      "pry",
      "bundler"
    ]
    packages.each do |pack|
        system %Q[gem install #{pack}]
    end
end

desc "Install ruby"
task :install_ruby do
    system %Q[ruby-install -s build ruby stable]
    system %Q[rm -rf build]
end

