require './dotfiles'

task :install do
  linkables("web").each do |item|
    if item == 'web/vimperator'
      target = "#{ENV["HOME"]}/.vimperator"
      backup target
      `mkdir -p #{target}/`
      install_item 'web/vimperator/colors', "#{target}/colors"
      install_item 'web/vimperator/plugin', "#{target}/plugin"
    else
      install_item item
    end
  end
end

task :uninstall do
  linkables("web").each do |item|
    if item == 'web/vimperator'
      target = "#{ENV["HOME"]}/.vimperator"
      uninstall_item 'web/vimperator/colors', "#{target}/colors"
      uninstall_item 'web/vimperator/plugin', "#{target}/plugin"
      restore target
    else
      uninstall_item item
    end
  end
end
